baseURL = "https://loumloum.github.io"
languageCode = "fr-ch"
title = "L'UX Ã©thique"
theme = "PaperMod"
themesDir = "themes"
cannonifyURLs = true

[taxonomies]
category = "categories"
tag = "tags"

[[menu.main]]
identifier = 'categories'
name = 'categories'
url = '/categories/'
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

